#  Please refer to the wiki(https://github.com/nlef/moonraker-telegram-bot/wiki) for detailed information on how to configure the bot

[bot]
server: localhost
bot_token: 8889337538:AAHibFovIkMQGxjggiu0pYOa-7r-HF943MI
chat_id: 8910642485

[camera]
host: http://localhost:8080/?action=stream
type: mjpeg

[progress_notification]
percent: 25
height: 0
time: 0

[timelapse]
cleanup: true
height: 0.2
time: 40 #0 for cinematic, was 30 trying to get the klipper temp limit active to not appear so increased to 40
target_fps: 15 #20 for cinematic, was 20 trying to get the klipper temp limit active to not appear so decreased to 15.
min_lapse_duration: 10
max_lapse_duration: 45 #was 60 trying to get the klipper temp limit active to not appear so decreased to 45



